version: '3'
networks:
  proxy:
    external: true
  
services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - API_SERVER=https://tjapi.dev-hk.bviews.top
        - SITE=default
        - SITE_NAME=测试糖吉慢病服务系统
        - IM_APP_ID=1400759217
    image: ccr.ccs.tencentyun.com/tangji/tangji_web_staging
    platform: linux/amd64
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tjweb.rule=Host(`tjweb.dev-hk.bviews.top`)"
      - "traefik.http.routers.tjweb.entrypoints=websecure"
      - "traefik.http.routers.tjweb.service=tjweb-service"
      - "traefik.http.services.tjweb-service.loadbalancer.server.port=80"
      - "traefik.http.routers.tjweb.tls.certresolver=myresolver"

  nginx-admin:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - API_SERVER=https://api.staging.jixianghealth.com
        - SITE=admin
        - SITE_NAME=测试糖吉后台
        - IM_APP_ID=1400759217
    image: ccr.ccs.tencentyun.com/tangji/tangji_admin_staging
    platform: linux/amd64
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tjadmin.rule=Host(`tjadmin.dev-hk.bviews.top`)"
      - "traefik.http.routers.tjadmin.entrypoints=websecure"
      - "traefik.http.routers.tjadmin.service=tjadmin-service"
      - "traefik.http.services.tjadmin-service.loadbalancer.server.port=80"
      - "traefik.http.routers.tjadmin.tls.certresolver=myresolver"
